name: Bug Report
description: Report a bug encountered while using Uno Platform Studio.
labels: [kind/bug, triage/untriaged, difficulty/tbd]
body:
  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior
      description: Describe how the issue manifests while using [Uno Platform Studio](https://aka.platform.uno/studio).

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe what the desired behavior should be when using [Uno Platform Studio](https://aka.platform.uno/studio).

  - type: dropdown
    id: tools
    attributes:
      label: Which tool(s) are affected?
      description: ([Hot Design®](https://aka.platform.uno/hot-design), [Hot Reload](https://aka.platform.uno/hot-reload), or [Design-to-Code](https://aka.platform.uno/Design-to-Code))
      multiple: true
      options:
        - Hot Design®
        - Hot Reload
        - Design-to-Code

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce it (as minimally and precisely as possible)
      description: |
        Please provide the **STEPS TO REPRODUCE** and any relevant details about the issue:
        - Outline the steps required to reproduce the issue.
        - Include any code snippets, screenshots, videos, or additional context that can help us understand and replicate the problem.

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Please provide steps to workaround this problem if possible.

  - type: checkboxes
    id: renderer
    attributes:
      label: Renderer
      description: [More info](https://aka.platform.uno/how-uno-works#rendering-the-ui)
      options:
        - label: Skia
        - label: Native

  - type: dropdown
    id: platforms
    attributes:
      label: Affected platforms
      description: |
        **Important Notes for Hot Design®:** 
        - To start using **Hot Design**, ensure you are signed in with your Uno Platform account. Follow [these instructions](https://aka.platform.uno/account-access) to register and sign in.  
        - Hot Design is available on all platforms. See the list of [known issues](https://github.com/unoplatform/studio/issues/66).  
        - Hot Design **does not support C# Markup** and is **only available with XAML and .NET 9**.  
        - Hot Design is **not available for the WinAppSDK target framework (`netX.0-windowsX.X.X`)** at this time.  
        - Hot Design relies on **[Hot Reload](https://aka.platform.uno/hot-reload)** for updates, so be sure to check the [current support for your OS, IDE, and target platforms](https://aka.platform.uno/hot-reload#supported-features-per-os) before testing.
      multiple: true
      options:
        - Desktop - `net9.0-desktop` (on Windows)
        - Desktop - `net9.0-desktop` (on macOS)
        - Desktop - `net9.0-desktop` (on X11)
        - Desktop - `net9.0-desktop` (on Linux Framebuffer)
        - WebAssembly - `net9.0-browserwasm`
        - Android - `net9.0-android`
        - iOS - `net9.0-ios`
        - Windows App SDK (WinAppSDK) - `net9.0-windows10.0.X`

  - type: input
    id: uno-sdk-version
    attributes:
      label: Uno.Sdk version
      description: Specify the version of Uno.Sdk being used, as listed in the `global.json` file of your solution.

  - type: dropdown
    id: ide
    attributes:
      label: IDE used
      multiple: true
      options:
        - Visual Studio 2022
        - Visual Studio Code on Windows
        - Visual Studio Code on macOS
        - Visual Studio Code on Linux
        - Rider on Windows
        - Rider on macOS
        - Rider on Linux

  - type: input
    id: ide-version
    attributes:
      label: IDE version
      description: Specify the version of the IDE you were using.

  - type: input
    id: uno-platform-extension-version
    attributes:
      label: Uno Platform Extension version
      description: Specify the version of the Uno Platform Extension you are using with your IDE.

  - type: textarea
    id: plugins
    attributes:
      label: Relevant plugins
      description: For example, ReSharper version X or any other tools affecting your workflow.

  - type: textarea
    id: additional-info
    attributes:
      label: Anything else we need to know?
      description: Provide any additional details or context that could help us investigate the issue.
