name: Bug Report
description: Report a bug encountered while using Uno Platform Studio.
labels: [kind/bug, triage/untriaged, difficulty/tbd]
body:
  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior
      description: Describe how the issue manifests while using Uno Platform Studio.

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe what the desired behavior should be when using Uno Platform Studio.

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce it (as minimally and precisely as possible)
      description: |
        Please provide the **STEPS TO REPRODUCE** and any necessary details about the issue:

        - Which tool were you using? (Hot Design™, Hot Reload, or Design-to-Code)
        - Steps to reproduce the issue.
        - Provide any code snippets, screenshots, videos or additional context that would help us understand how to reproduce the issue.

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Please provide steps to workaround this problem if possible.

  - type: dropdown
    id: tools
    attributes:
      label: Which tool(s) are affected?
      multiple: true
      options:
        - Hot Design™
        - Hot Reload
        - Design-to-Code

  - type: dropdown
    id: platforms
    attributes:
      label: Affected platforms
      description: |
        **Note for Hot Design™:**

        At the current stage of the Hot Design™ beta, only the **Desktop** platform is supported. Other platforms are undergoing stabilization for Hot Design support and will be available in future updates.

        For now, you can use the **Desktop** platform to create your UI with the runtime visual designer. Once you’re satisfied with your design, you can test the app on other platforms by launching it as you would normally.
      multiple: true
      options:
        - Desktop (Skia)
        - Windows
        - WebAssembly
        - Android
        - iOS
        - macOS (Catalyst)

  - type: input
    id: uno-sdk-version
    attributes:
      label: Uno.Sdk version
      description: Specify the version of Uno.Sdk being used, as listed in the `global.json` file of your solution.

  - type: dropdown
    id: ide
    attributes:
      label: IDE used
      multiple: true
      options:
        - Visual Studio 2022
        - Visual Studio Code on Windows
        - Visual Studio Code on macOS
        - Visual Studio Code on Linux
        - Rider on Windows
        - Rider on macOS
        - Rider on Linux

  - type: input
    id: ide-version
    attributes:
      label: IDE version
      description: Specify the version of the IDE you were using.

  - type: input
    id: uno-platform-extension-version
    attributes:
      label: Uno Platform Extension version
      description: Specify the version of the Uno Platform Extension you are using with your IDE.

  - type: textarea
    id: plugins
    attributes:
      label: Relevant plugins
      description: For example, ReSharper version X or any other tools affecting your workflow.

  - type: textarea
    id: additional-info
    attributes:
      label: Anything else we need to know?
      description: Provide any additional details or context that could help us investigate the issue.
