name: Documentation Request
description: Request an enhancement or clarification for the Uno Platform Studio documentation.
labels: [kind/consumer-experience, kind/documentation, triage/untriaged, difficulty/tbd]
body:
  - type: textarea
    id: documentation-request
    attributes:
      label: What do you need clarification or enhancement on?
      description: Describe in detail the documentation topic or section that needs improvement or clarification.

  - type: dropdown
    id: tools
    attributes:
      label: Which tool(s) are affected?
      description: ([Hot Design速](https://aka.platform.uno/hot-design), [Hot Reload](https://aka.platform.uno/hot-reload), or [Design-to-Code](https://aka.platform.uno/Design-to-Code))
      multiple: true
      options:
        - Hot Design速
        - Hot Reload
        - Design-to-Code

  - type: textarea
    id: documentation-concern
    attributes:
      label: What is your concern?
      description: |
        Please describe your concern in detail. Examples of topics you could include:
        - Getting started with Uno Platform Studio
        - Using Hot Design速
        - Using Hot Reload
        - Using Design-to-Code
        - Supported platforms or tools
        - Best practices or workflows
        - Other (please specify)
      render: dynamic

  - type: checkboxes
    id: documentation-renderer
    attributes:
      label: Renderer
      description: |
        [More info](https://aka.platform.uno/how-uno-works#rendering-the-ui)
      options:
        - label: Skia
        - label: Native

  - type: dropdown
    id: documentation-platforms
    attributes:
      label: For which platform(s)?
      description: |
        **Important Notes for Hot Design速:** 
        - To start using **Hot Design**, ensure you are signed in with your Uno Platform account. Follow [these instructions](https://aka.platform.uno/account-access) to register and sign in.  
        - Hot Design is available on all platforms. See the list of [known issues](https://github.com/unoplatform/studio/issues/66).  
        - Hot Design **does not support C# Markup** and is **only available with XAML and .NET 9**.  
        - Hot Design is **not available for the WinAppSDK target framework (`netX.0-windowsX.X.X`)** at this time.  
        - Hot Design relies on **[Hot Reload](https://aka.platform.uno/hot-reload)** for updates, so be sure to check the [current support for your OS, IDE, and target platforms](https://aka.platform.uno/hot-reload#supported-features-per-os) before testing.
      multiple: true
      options:
        - Desktop - net9.0-desktop (on Windows)
        - Desktop - net9.0-desktop (on macOS)
        - Desktop - net9.0-desktop (on X11)
        - Desktop - net9.0-desktop (on Linux Framebuffer)
        - WebAssembly - net9.0-browserwasm
        - Android - net9.0-android
        - iOS - net9.0-ios
        - Windows App SDK (WinAppSDK) - net9.0-windows10.0.X

  - type: textarea
    id: additional-info
    attributes:
      label: Is there anything else we need to know?
      description: Include any notes, further explanations, or references that might help contributors understand your request.
