name: Documentation Issue
description: Report an issue with the Uno Platform Studio documentation.
labels: [kind/consumer-experience, kind/documentation, triage/untriaged, difficulty/tbd]
body:
  - type: input
    id: documentation-page
    attributes:
      label: On which page?
      description: Provide the URL or title of the documentation page where you found the issue.

  - type: dropdown
    id: tools
    attributes:
      label: Which tool(s) are affected?
      description: ([Hot Design™](https://aka.platform.uno/hot-design), [Hot Reload](https://aka.platform.uno/hot-reload), or [Design-to-Code](https://aka.platform.uno/Design-to-Code))
      multiple: true
      options:
        - Hot Design™
        - Hot Reload
        - Design-to-Code

  - type: textarea
    id: documentation-problem
    attributes:
      label: What's wrong?
      description: Describe the problem or issue with the documentation in detail.

  - type: textarea
    id: additional-feedback
    attributes:
      label: Any feedback?
      description: Provide additional feedback, suggestions, or anything else we need to know.
