name: Documentation Request
description: Request an enhancement or clarification for the Uno Platform Studio documentation.
labels: [kind/consumer-experience, kind/documentation, triage/untriaged, difficulty/tbd]
body:
  - type: textarea
    id: documentation-request
    attributes:
      label: What do you need clarification or enhancement on?
      description: Describe in detail the documentation topic or section that needs improvement or clarification.

  - type: dropdown
    id: tools
    attributes:
      label: Which tool(s) are affected?
      description: ([Hot Design™](https://aka.platform.uno/hot-design), [Hot Reload](https://aka.platform.uno/hot-reload), or [Design-to-Code](https://aka.platform.uno/Design-to-Code))
      multiple: true
      options:
        - Hot Design™
        - Hot Reload
        - Design-to-Code

  - type: textarea
    id: documentation-concern
    attributes:
      label: What is your concern?
      description: |
        Please describe your concern in detail. Examples of topics you could include:
        - Getting started with Uno Platform Studio
        - Using Hot Design™
        - Using Hot Reload
        - Using Design-to-Code
        - Supported platforms or tools
        - Best practices or workflows
        - Other (please specify)
      render: dynamic

  - type: dropdown
    id: documentation-platforms
    attributes:
      label: For which platform(s)?
      description: |
        **Note for Hot Design™:**

        At the current stage of the Hot Design™ beta, only the **Desktop** platform is supported. Other platforms are undergoing stabilization for Hot Design support and will be available in future updates.

        For now, you can use the **Desktop** platform to create your UI with the runtime visual designer. Once you’re satisfied with your design, you can test the app on other platforms by launching it as you would normally.
      multiple: true
      options:
        - Desktop (Skia)
        - Windows
        - WebAssembly
        - Android
        - iOS
        - macOS (Catalyst)

  - type: textarea
    id: additional-info
    attributes:
      label: Is there anything else we need to know?
      description: Include any notes, further explanations, or references that might help contributors understand your request.
