name: Enhancement Request
description: Suggest an enhancement to Uno Platform Studio.
labels: [kind/enhancement, triage/untriaged, difficulty/tbd]
body:
  - type: textarea
    id: enhancement-description
    attributes:
      label: What feature or functionality would you like to see added?
      description: Describe in detail what feature or functionality you feel is missing from [Uno Platform Studio](https://aka.platform.uno/studio).

  - type: textarea
    id: enhancement-use-case
    attributes:
      label: Why is this enhancement needed?
      description: Explain the use case or problem this enhancement would address and how it would improve your workflow.

  - type: dropdown
    id: tools
    attributes:
      label: Which tool(s) are affected?
      description: ([Hot Design®](https://aka.platform.uno/hot-design), [Hot Reload](https://aka.platform.uno/hot-reload), or [Design-to-Code](https://aka.platform.uno/Design-to-Code))
      multiple: true
      options:
        - Hot Design®
        - Hot Reload
        - Design-to-Code

  - type: checkboxes
    id: enhancement-renderer
    attributes:
      label: Related Renderer
      description: |
        [More info](https://aka.platform.uno/how-uno-works#rendering-the-ui)
      options:
        - label: Skia
        - label: Native

  - type: dropdown
    id: enhancement-platforms
    attributes:
      label: For which platform(s)?
      description: |
        **Important Notes for Hot Design®:** 
        - To start using **Hot Design**, ensure you are signed in with your Uno Platform account. Follow [these instructions](https://aka.platform.uno/account-access) to register and sign in.  
        - Hot Design is available on all platforms. See the list of [known issues](https://github.com/unoplatform/studio/issues/66).  
        - Hot Design **does not support C# Markup** and is **only available with XAML and .NET 9**.  
        - Hot Design is **not available for the WinAppSDK target framework (`netX.0-windowsX.X.X`)** at this time.  
        - Hot Design relies on **[Hot Reload](https://aka.platform.uno/hot-reload)** for updates, so be sure to check the [current support for your OS, IDE, and target platforms](https://aka.platform.uno/hot-reload#supported-features-per-os) before testing.
      multiple: true
      options:
        - Desktop - net9.0-desktop (on Windows)
        - Desktop - net9.0-desktop (on macOS)
        - Desktop - net9.0-desktop (on X11)
        - Desktop - net9.0-desktop (on Linux Framebuffer)
        - WebAssembly - net9.0-browserwasm
        - Android - net9.0-android
        - iOS - net9.0-ios
        - Windows App SDK (WinAppSDK) - net9.0-windows10.0.X

  - type: textarea
    id: enhancement-additional-info
    attributes:
      label: Is there anything else we need to know?
      description: Include any notes, further explanations, or references that might help contributors understand your request.
